### PR TITLE
fix(topCards - design): make it pretty and readable

### PR DESCRIPTION
**Pull request by iamruhul**
This PR changes the layout and the readability of the TopCards to make it a little better using `flex-flow: row-wrap` and `text-shadow` respectively and also tweaks many small things to make it look better. 

screenshot from 2018-11-16 13-03-35  
screenshot from 2018-11-16 13-08-34

### CODE REVIEW

**Comment by iamruhul** [comment]
please see issue #15

**Comment by zonayedpca** [comment]
Good Job Brother... :)

**Comment by iamruhul** [comment]
thank u so much brother...

**Comment by iamruhul** [comment]
this is a start

**Pull request merged**
