### PR TITLE
[ADD] Atom Shortcut for Mac

### PR DESCRIPTION
**Pull request by iamraufu**

### CODE REVIEW

**Review by sabbirshawon — CHANGES_REQUESTED** [review]
please remove empty data..

**Comment by iamraufu** [comment]
> please remove empty data..

Done and intended
Thanks

**Comment by iamraufu** [comment]
@sabbirshawon All okay to be merged?

**Review by sabbirshawon — APPROVED** [review]
THANKS FOR YOUR CONTRIBUTIONS

**Pull request merged**
