### PR TITLE
Some git commands added into git.json file.

### PR DESCRIPTION
**Pull request by developer-sayed**
I have added some git commands in git.json file on my commit.. I have checked the JSON file in JSONLint and it's a valid JSON.. Please have a look.. Thank you..

### CODE REVIEW

**Comment by zonayedpca** [comment]
Great contribution brother... But we need a little bit update here. Please be consistent with the styling of the contents. Please check these lines: 27, 31, 43, 55, 95, 99, 103, 135, 163, 171 and 175

**Comment by developer-sayed** [comment]
>File is updated..Please have a look now.

**Comment by zonayedpca** [comment]
Thanks brother... Great one... Please share with your friends as well... Hope to see more contribution in future...

**Comment by developer-sayed** [comment]
> Thanks brother... Great one... Please share with your friends as well... Hope to see more contribution in future...

Thank you so much and credit goes to your tuts -- https://with.zonayed.me/bn/%E0%A6%B8%E0%A6%AB%E0%A6%9F-%E0%A6%B8%E0%A7%8D%E0%A6%95%E0%A6%BF%E0%A6%B2/%E0%A6%8F%E0%A6%95-%E0%A6%AA%E0%A6%B2%E0%A6%95%E0%A7%87-%E0%A6%97%E0%A6%BF%E0%A6%9F-git-%E0%A6%93-%E0%A6%97%E0%A6%BF%E0%A6%9F%E0%A6%B9%E0%A6%BE%E0%A6%AC-github%E2%80%8A-%E2%80%8A%E0%A6%AA/?source=post_page---------------------------

**Pull request merged**
