### PR TITLE
[Add] Flutter-cheat-sheet doc

### PR DESCRIPTION
**Pull request by lukmanhossain**

### CODE REVIEW

**Review by sabbirshawon — CHANGES_REQUESTED** [review]
please don't use another extension

**Review by zonayedpca — CHANGES_REQUESTED** [review]
Although this is a draft, please use a browser friendly format like .txt or .md file...

Thanks

**Comment by HridoyHazard** [comment]
looks like he only added cheatsheet in english and also in docx format. can i take this and make a proper cheatsheet in bangla and make another pr ? @sabbirshawon  vai @zonayedpca  vai

**Comment by zonayedpca** [comment]
> looks like he only added cheatsheet in english and also in docx format. can i take this and make a proper cheatsheet in bangla and make another pr ? @sabbirshawon vai @zonayedpca vai

Please go ahead bhai, also mention this PR... Thanks

**Comment by zonayedpca** [comment]
I have labeled this as hacktoberfest accepted but couldn't merge this as .docx file format is not browser friendly and will give hard time to the contributors to convert it to real cheatsheet. But nonetheless still a good contribution. Thanks

**Comment by zonayedpca** [comment]
Sorry inactive for a very long time, closing this one

**Pull request closed without merging**
