### PR TITLE
New Navbar, Masthead design and more!!!

### PR DESCRIPTION
**Pull request by iamruhul**
here's the gif - >

peek 2018-12-09 22-24

### CODE REVIEW

**Comment by iamruhul** [comment]
changed `add another` -> `contribute`

**Comment by zonayedpca** [comment]
Thanks for your great contribution... But I think this intro area doesn't aligned properly... It should be placed in a perfect location so that it actually looks symmetric. The Texts can be placed just in center or left side, but properly aligned with other contents. Also spacing from all the side(top, bottom, left, right) should be same or have some meaning at least. 
image
And also Search should be easily accesable as it necessary for this website. Extra one step is bad User Experience I think... Please do review once again 👍

**Comment by iamruhul** [comment]
right .... I put it there cuz it looked good to me

**Comment by iamruhul** [comment]
is it good this way ???
screenshot from 2018-12-09 23-02-21

**Comment by iamruhul** [comment]
github is not a good place to chat ... let's discuss it in messenger / slack?

**Comment by iamruhul** [comment]
> Thanks for your great contribution... But I think this intro area doesn't aligned properly... It should be placed in a perfect location so that it actually looks symmetric. The Texts can be placed just in center or left side, but properly aligned with other contents. Also spacing from all the side(top, bottom, left, right) should be same or have some meaning at least.
> image
> And also Search should be easily accesable as it necessary for this website. Extra one step is bad User Experience I think... Please do review once again

thank u for your review/... i'll  review it again..

**Comment by zonayedpca** [comment]
I have a really hard exam coming up next, I will discuss with you definitely. Please keep it in your mind we want more modern, clean and simple design... Please take some ideas from dribbble, behance or material.uplabs.com if you need and also I think we should go for Google's Standard Material Design which will give us pretty much a better clean design

**Comment by iamruhul** [comment]
> I have a really hard exam coming up next, I will discuss with you definitely. Please keep it in your mind we want more modern, clean and simple design... Please take some ideas from dribbble, behance or material.uplabs.com if you need and also I think we should go for Google's Standard Material Design which will give us pretty much a better clean design

Good luck for your exam... I will make the necessary changes ....

 here are the changes -->

* intro should have meaningful spacing
* searchbar should be accessible

**Pull request closed without merging**
