### PR TITLE
markdown cheatsheet added.

### PR DESCRIPTION
**Pull request by ebnsina**

### CODE REVIEW

**Comment by shabab477** [comment]
Thanks for the contribution but this PR branch was not properly re-based. Can you please re base with the upstream? Thanks

**Comment by ebnsina** [comment]
I never contribute before. How do I do that?
Best Regards,

*AHNM EBN SINA <http://ebnsina.info>*
Web Developer
Lets Learn Coding Ltd <https://www.letslearncoding.org/>

**Comment by shabab477** [comment]
Follow these steps:
1. `git checkout develop` --> This checkouts to the develop branch
2. `git remote add upstream https://github.com/devsonket/devsonket.github.io.git` --> this adds a new remote repo named upstream just like creating origin
3. `git reset --hard develop` --> Warning this will reset everything back to develop. Please copy your contribution to some other folder. There is a way to avoid this but I am just following the easiest path.
4. `git pull upstream develop --rebase` --> This will rebase everything in sync with the upstream, i.e, the remote repo
5. `git checkout -b feature/add-markdown-cheat-sheet` --> This creates a new branch

Commit your contribution in this branch and create a PR referencing the develop branch of upstream. 

Best of luck. Looking forward to your contribution. :smile:

**Comment by shabab477** [comment]
Did you push the updated branch to your repo?

**Comment by ebnsina** [comment]
I just follow your steps (commands).
Here is my fork repo: (https://github.com/ebnsina/devsonket.github.io).
It shows my pushes and commits.

Best Regards,
*AHNM EBN SINA <http://ebnsina.me>*
Web Developer
Lets Learn Coding Ltd <https://www.letslearncoding.org/>

**Pull request closed without merging**
