### PR TITLE
Update golang.json

### PR DESCRIPTION
**Pull request by irezaul**
সময় অতিবাহিত কৌশল ( Time elapsed trick )

### CODE REVIEW

**Comment by sabbirshawon** [comment]
Fix the problem and send pr again @irezaul

**Comment by mahiuddin-dev** [comment]
`    "items": {
            "definition": "Utility",
            "code": "func TrackTime(pre time.Time) time.Duration {\n
                elapsed := time.Since(pre)\n
                fmt.Println("elapsed:", elapsed)\n\n

                return elapsed\n }\n\n

                func TestTrackTime(t *testing.T) {\n
                    defer TrackTime(time.Now()) // <=== THIS \n\n

                    time.Sleep(500 * time.Millisecond)\n
                   }"
            }
        }
`

Maybe the problem here. It should be 
`        {
            "title": "",
            "items": [{
                    "definition": "definition here",
                    "code": "code here"
                },
            ]
        },
`

**Comment by mahiuddin-dev** [comment]
Maybe the problem here.
```
"items": {
            "definition": "Utility",
            "code": "func TrackTime(pre time.Time) time.Duration {\n
                elapsed := time.Since(pre)\n
                fmt.Println("elapsed:", elapsed)\n\n

                return elapsed\n }\n\n

                func TestTrackTime(t *testing.T) {\n
                    defer TrackTime(time.Now()) // <=== THIS \n\n

                    time.Sleep(500 * time.Millisecond)\n
                   }"
            }
        }
```

It should be like this

```    
      {
            "title": "title",
            "items": [{
                    "definition": "definition here",
                    "code": "code here"
                }
            ]
        }
```

**Review by irezaul — COMMENTED** [review]
Time elapsed trick code correction

**Pull request closed without merging**
