### PR TITLE
New navbar, Buttons, header background and content card!!

### PR DESCRIPTION
**Pull request by iamruhul**
This PR adds this nice looking buttons, navbar and the material(ish) content card!

screenshot_ _
---

---

---

---

Here's the content card - 

screenshot_ _

### CODE REVIEW

**Comment by zonayedpca** [comment]
Good Job Brother... If you want to implement materialish design, then I think we should apply this design to all over the website... Are you planning to change all of them? Please let me know...

**Comment by iamruhul** [comment]
I will be changing a lot (I mean a aa a a a a a lot) and a near to full redesign is coming soon

**Comment by zonayedpca** [comment]
we have colorPref property in our every cheatsheet... Please consider using it somewhere if you can... It will be great... And should we merge this pull request right now or we should wait for all the changes? What do you think?

**Comment by iamruhul** [comment]
What is `colorPref` used for??

**Comment by zonayedpca** [comment]
Please update all the design as soon as possible. The new design is not consistent all over the site. Also, this design doesn't provide enough support for mobile devices as well as print format. Please update them as soon as possible..

**Comment by zonayedpca** [comment]
Don't forget about the print format, this one is important as well...

**Comment by zonayedpca** [comment]
This what it looks like right now:
image

**Comment by iamruhul** [comment]
okay

**Pull request merged**
